export const R2 = "https://pub-619599119b654aa687d85cb7a08febcb.r2.dev"
// export const BACKEND_URL="http://localhost:8000/api"
export const BACKEND_URL="https://check.globalelectronicsolutions.in/api"
export const EMAIL="https://test3.globalelectronicsolutions.in/"
// export const BACKEND_URL="https://gesbackend.onrender.com/api"