export const R2 = "https://pub-148b30caae4a4303b96f2f375d5f82c0.r2.dev"
// export const BACKEND_URL="http://localhost:8000/api"
export const BACKEND_URL="https://check.globalelectronicsolutions.in/api"
export const EMAIL="https://test3.globalelectronicsolutions.in/"
// export const BACKEND_URL="https://gesbackend.onrender.com/api"