name: Build and Deploy to Docker Hub

on:
  push:
    branches:
      - main  # Adjusted to trigger on pushes to master
env:
  RESEND_API_KEY: ${{ secrets.RESEND_API_KEY}}    

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
    - name: Check Out Repo
      uses: actions/checkout@v2

    - name: 'Create env file'
      run:
          touch .env
          echo RESEND_API_KEY=${{ secrets.RESEND_API_KEY }} >> .env
          cat .env
          
    - name: Log in to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    - name: 'Create env file'
      run:
          touch .env
          echo RESEND_API_KEY=${{ secrets.RESEND_API_KEY }} >> .env
          cat .env
    - name: Build and Push Docker image
      uses: docker/build-push-action@v2
      with:
        context: .
        file: ./dockerfile  # Corrected to match your file name
        push: true
        tags: sudheer007dfs/ges-frontend:v3

    - name: Verify Pushed Image
      run: docker pull sudheer007dfs/my-app:latest

    - name: Deploy to EC2
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USERNAME }}
        key: ${{ secrets.SSH_USERNAMEE}}  # Corrected the secret key reference
        script: |
          docker compose up
